version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/wanderlust
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

